/** @format */

export const FULL = {
	padding: "12px",
}

export const COLORS = {
	text: "gray",
	important: "#FFFFFF",
}

export const hackLines = [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	"Vivamus a libero nec turpis auctor hendrerit a non libero.",
	"In fermentum lorem et pretium lobortis.",
	"Nam a lorem eget libero malesuada tincidunt.",
	"Nam semper metus sit amet eros interdum varius.",
	"Nullam dignissim dui quis nisl volutpat, in dapibus velit efficitur.",
	"Duis tristique ante eget ligula dapibus dapibus.",
	"Sed accumsan magna vitae enim ultrices, non suscipit neque feugiat.",
	"Curabitur eget erat fermentum ipsum molestie egestas egestas sed neque.",
	"Pellentesque non erat et leo mollis pulvinar.",
	"Donec eleifend justo in sapien feugiat, non finibus diam dignissim.",
	"Donec pulvinar enim et sem tincidunt blandit.",
	"Sed id est vitae mi volutpat tristique sit amet vel augue.",
	"Etiam fringilla nisi nec libero blandit, sit amet ornare lectus pretium.",
	"Etiam non urna nec elit sodales finibus.",
	"Sed sit amet lectus vitae arcu facilisis mattis.",
	"Nunc lobortis mi eget pretium cursus.",
	"Praesent placerat quam sit amet eros pretium tempor.",
	"Ut tempus risus eget metus porttitor accumsan.",
	"Aenean sed nulla non mi scelerisque blandit.",
	"Duis egestas libero vel dui vestibulum, sed scelerisque nibh tincidunt.",
	"Pellentesque malesuada risus sit amet massa dapibus varius.",
	"Nullam tempor tellus quis ligula hendrerit pharetra in ac elit.",
	"Nam vestibulum nulla a ipsum ultricies condimentum.",
	"Nulla quis diam auctor risus varius imperdiet condimentum eget sem.",
	"Quisque ut purus quis dolor porttitor malesuada.",
	"Cras suscipit arcu nec ornare porttitor.",
	"Aliquam hendrerit turpis quis nulla ornare, a semper eros dignissim.",
	"Vestibulum laoreet massa eu finibus maximus.",
	"Maecenas mollis lectus vitae auctor vestibulum.",
	"Etiam lacinia lacus quis nisl auctor, et maximus felis volutpat.",
	"Suspendisse et nulla aliquam, aliquam metus vel, convallis augue.",
	"Aenean dapibus velit sit amet risus luctus efficitur eu at est.",
	"Vestibulum quis mauris laoreet ex tincidunt lobortis in quis dolor.",
	"Aliquam elementum orci eget ligula consequat euismod.",
	"Nunc rhoncus ex sed mauris tempor porttitor.",
	"Aenean gravida ante aliquam massa fermentum hendrerit.",
	"Vestibulum aliquet est bibendum consequat accumsan.",
	"Fusce placerat metus nec lobortis fermentum.",
	"Phasellus suscipit ex eget enim tincidunt suscipit.",
	"Nam vitae sem non nulla convallis fermentum.",
	"Fusce vitae dolor maximus libero dapibus aliquet ac ac quam.",
	"Quisque a mauris tempor, laoreet risus sit amet, pretium ligula.",
	"Sed ac ante et risus blandit dictum.",
	"Mauris aliquet dolor sed interdum porta.",
	"Praesent facilisis nunc ac diam maximus dignissim.",
	"Morbi tristique est a est maximus, ut cursus metus luctus.",
	"Mauris congue orci vitae elementum hendrerit.",
	"Proin aliquet magna vitae ipsum faucibus, et finibus ex mollis.",
	"Morbi mattis augue at orci ultrices, quis lacinia tellus mattis.",
	"Morbi quis augue ultricies, malesuada enim vitae, pulvinar nibh.",
	"Aenean porttitor tellus ullamcorper enim efficitur, vitae vehicula elit placerat.",
	"Nullam lobortis justo placerat sapien egestas, in pretium mauris condimentum.",
	"Nullam tincidunt lorem ut odio gravida, nec congue risus posuere.",
	"Nam accumsan dui non nisi maximus, a venenatis nisi gravida.",
	"Morbi suscipit neque vitae purus aliquam molestie.",
	"Proin porta metus pharetra, scelerisque felis quis, tincidunt eros.",
	"Etiam fringilla lectus sed neque posuere malesuada.",
	"Sed nec velit ac mi euismod sollicitudin.",
	"Vestibulum at magna tincidunt, elementum arcu vel, maximus nibh.",
	"Nullam ultricies lorem et nulla efficitur, vel tempus lectus cursus.",
	"Sed fermentum nulla sit amet malesuada laoreet.",
	"Integer sit amet elit sagittis, accumsan magna vel, aliquet neque.",
	"Vivamus condimentum nisl quis tincidunt mollis.",
	"Donec condimentum mi eget nunc euismod, volutpat suscipit sapien commodo.",
	"Vestibulum malesuada massa a nulla imperdiet, nec pretium ex viverra.",
	"Aliquam vitae nunc eget erat euismod consequat vel vestibulum eros.",
	"Vivamus gravida orci id diam sodales tristique.",
	"Sed pulvinar erat quis euismod gravida.",
]
